spring:
  application:
    name: KLT Converter
  data:
    redis:
      host: 192.168.1.196
      port: 6379

#
#server:
#  port: 8080
#  servlet:
#    context-path: /klt



external:
  currencies:
    base-url: http://localhost:9090/
    forex: forex/currencies